### ISSUE TITLE
Formulaire d'inscription

### ISSUE THREAD

**Issue by ThomasEscorne** [2gacem7/brocantekram#1]
Il n'y a pas de label au dessus des champs ce qui rend la compréhension du form difficilement compréhensible quand tous les champs sont remplis.
Ajoute des labels en plus des placeholders dans les champs

**Comment by 2gacem7** [comment]
Les labels ont été ajouté.

**Comment by 2gacem7** [comment]
> Il n'y a pas de label au dessus des champs ce qui rend la compréhension du form difficilement compréhensible quand tous les champs sont remplis.
> Ajoute des labels en plus des placeholders dans les champs

Les labels ont été ajouté.
